(()=>{
const repo='AradZabeti/AradZabeti';
const api='https://api.github.com/repos/'+repo;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>new Intl.NumberFormat().format(n||0);
const ago=d=>{const x=(Date.now()-new Date(d).getTime())/1000;if(x<60)return 'just now';if(x<3600)return Math.floor(x/60)+'m ago';if(x<86400)return Math.floor(x/3600)+'h ago';return Math.floor(x/86400)+'d ago'};
async function get(path){const r=await fetch(api+path,{headers:{Accept:'application/vnd.github+json'}});if(!r.ok)throw Error(r.status);return r.json()}
function mount(){let root=document.querySelector('#github-live');if(!root)return null;let panel=document.querySelector('#activity-live');if(!panel){panel=document.createElement('div');panel.id='activity-live';panel.className='activity-live';root.appendChild(panel)}return panel}
async function load(){const root=mount();if(!root)return;root.innerHTML='<div class="activity-loading">LOADING ACTIVITY MATRIX…</div>';try{
const [repoData,activity,languages,commits]=await Promise.all([get(''),get('/stats/commit_activity'),get('/languages'),get('/commits?per_page=8')]);
const weeks=Array.isArray(activity)?activity.slice(-26):[];const values=weeks.flatMap(w=>w.days||[]);const max=Math.max(1,...values);const total=weeks.reduce((a,w)=>a+(w.total||0),0);const recent=commits?.[0];
const langEntries=Object.entries(languages||{}).sort((a,b)=>b[1]-a[1]).slice(0,5);const langTotal=langEntries.reduce((a,x)=>a+x[1],0)||1;
root.innerHTML='<div class="activity-head"><div><span class="activity-kicker">ACTIVITY MATRIX</span><h3>GitHub Activity</h3><p>Live repository signals from the public GitHub API.</p></div><button class="activity-refresh" type="button">Refresh</button></div>'+
'<div class="activity-stats"><div><b>'+fmt(total)+'</b><span>26W COMMITS</span></div><div><b>'+fmt(repoData.stargazers_count)+'</b><span>STARS</span></div><div><b>'+fmt(repoData.forks_count)+'</b><span>FORKS</span></div><div><b>'+fmt(repoData.open_issues_count)+'</b><span>OPEN ISSUES</span></div></div>'+
'<div class="activity-grid"><section class="activity-card"><h4>COMMIT PULSE · 26 WEEKS</h4><div class="activity-bars">'+weeks.map(w=>(w.days||[]).map(v=>'<i style="height:'+Math.max(4,Math.round(v/max*100))+'%" title="'+v+' commits"></i>').join('')).join('')+'</div><div class="activity-axis"><span>26W AGO</span><span>NOW</span></div></section>'+
'<section class="activity-card"><h4>LANGUAGE MIX</h4><div class="lang-list">'+(langEntries.length?langEntries.map(([k,v])=>'<div class="lang-row"><div><span>'+esc(k)+'</span><b>'+Math.round(v/langTotal*100)+'%</b></div><em><i style="width:'+Math.max(3,v/langTotal*100)+'%"></i></em></div>').join(''):'<div class="activity-loading">No language data</div>')+'</div></section></div>'+
'<section class="activity-card latest"><h4>LATEST COMMIT</h4><a href="'+esc(recent?.html_url||('https://github.com/'+repo+'/commits/main'))+'" target="_blank" rel="noreferrer">'+esc(recent?.commit?.message?.split('\n')[0]||'No recent commit')+'</a><p>'+esc(recent?.sha?.slice(0,7)||'')+' · '+esc(recent?.commit?.author?.name||'GitHub')+' · '+(recent?.commit?.author?.date?ago(recent.commit.author.date):'')+'</p></section>';
root.querySelector('.activity-refresh').onclick=load;
}catch(e){root.innerHTML='<div class="activity-error">ACTIVITY UNAVAILABLE · '+esc(e.message)+'</div>'}}
const style=document.createElement('style');style.textContent=`.activity-live{margin-top:12px;border:1px solid #242832;border-radius:18px;background:linear-gradient(145deg,#0c1017,#090b10);padding:18px}.activity-head{display:flex;justify-content:space-between;align-items:end;gap:14px}.activity-kicker{color:#67e8f9;font:500 8px 'DM Mono';letter-spacing:.15em}.activity-head h3{margin:5px 0 4px;font:600 27px 'Space Grotesk';letter-spacing:-.05em}.activity-head p{margin:0;color:#697384;font:500 9px 'DM Mono'}.activity-refresh{border:1px solid #2b303b;background:#10131a;color:#dfe4ec;border-radius:8px;padding:8px 10px;font:500 9px 'DM Mono';cursor:pointer}.activity-stats{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:15px}.activity-stats div{padding:13px;border:1px solid #242a34;border-radius:11px;background:#0a0d13}.activity-stats b{display:block;font:600 21px 'Space Grotesk'}.activity-stats span{display:block;color:#697384;font:500 8px 'DM Mono';margin-top:3px}.activity-grid{display:grid;grid-template-columns:1.3fr .7fr;gap:9px;margin-top:9px}.activity-card{border:1px solid #242a34;border-radius:12px;background:#0a0d13;padding:14px}.activity-card h4{margin:0;color:#8993a3;font:500 8px 'DM Mono';letter-spacing:.12em}.activity-bars{height:112px;display:grid;grid-template-columns:repeat(26,1fr);grid-auto-flow:column;grid-template-rows:repeat(7,1fr);gap:4px;margin-top:13px;align-items:end}.activity-bars i{display:block;width:100%;min-height:3px;border-radius:3px;background:linear-gradient(180deg,#67e8f9,#7c5cff);opacity:.82}.activity-axis{display:flex;justify-content:space-between;color:#566171;font:500 7px 'DM Mono';margin-top:7px}.lang-list{margin-top:13px}.lang-row{margin-bottom:10px}.lang-row>div{display:flex;justify-content:space-between;color:#9ba4b2;font:500 8px 'DM Mono';margin-bottom:5px}.lang-row b{color:#e4e8ee}.lang-row em{display:block;height:4px;background:#1a1e27;border-radius:99px;overflow:hidden}.lang-row em i{display:block;height:100%;background:linear-gradient(90deg,#7c5cff,#67e8f9);border-radius:99px}.latest{margin-top:9px}.latest a{display:block;margin-top:10px;color:#f0f2f6;font:600 13px 'Space Grotesk';white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.latest p{margin:5px 0 0;color:#687282;font:500 8px 'DM Mono'}.activity-loading,.activity-error{padding:24px;color:#697384;font:500 9px 'DM Mono'}.activity-error{color:#f0a6b8}@media(max-width:800px){.activity-stats{grid-template-columns:repeat(2,1fr)}.activity-grid{grid-template-columns:1fr}}`;document.head.appendChild(style);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',load);else load();setInterval(load,600000)})();
