const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const palette=$('#palette'),terminal=$('#terminal'),input=$('#paletteInput'),tInput=$('#terminalInput'),out=$('#terminalOutput');
const commands=[
 ['About','Jump to About section','about'],['Skills','Jump to Toolkit','skills'],['Projects','Explore interactive projects','projects'],['Interactive Lab','Open experiments','lab'],['Contact','Jump to contact','contact'],['Terminal','Open developer terminal','terminal'],['GitHub','Open GitHub profile','github'],['KookTools','Open live music toolkit','kook']
];
function openPalette(){palette.classList.add('open');input.value='';renderCommands();setTimeout(()=>input.focus(),20)}
function closePalette(){palette.classList.remove('open')}
function renderCommands(){const q=input.value.toLowerCase().trim();const list=commands.filter(c=>(c[0]+' '+c[1]).toLowerCase().includes(q));$('#commandList').innerHTML=list.map((c,i)=>`<div class="cmd ${i===0?'selected':''}" data-cmd="${c[2]}"><b>${c[0]}</b><span>${c[1]}</span></div>`).join('')||'<div class="cmd"><span>No commands found</span></div>';selected=0;$$('.cmd').forEach(x=>x.onclick=()=>runCommand(x.dataset.cmd))}
function runCommand(cmd){closePalette();if(cmd==='terminal'){openTerminal();return}if(cmd==='github'){window.open('https://github.com/AradZabeti','_blank');return}if(cmd==='kook'){window.open('https://kooktools.netlify.app','_blank');return}document.getElementById(cmd)?.scrollIntoView({behavior:'smooth',block:'start'})}
$('#paletteBtn').onclick=openPalette;$('#labPalette').onclick=openPalette;$('#terminalOpen').onclick=openTerminal;$$('[data-terminal]').forEach(x=>x.onclick=openTerminal);input.oninput=renderCommands;
function openTerminal(){terminal.classList.add('open');setTimeout(()=>tInput.focus(),30)}function closeTerminal(){terminal.classList.remove('open')}
$('#terminalClose').onclick=closeTerminal;
function print(html){const d=document.createElement('div');d.innerHTML=html;out.appendChild(d);out.scrollTop=out.scrollHeight}
function help(){print('<div class="accent">Available commands:</div><div><b>help</b> — show commands</div><div><b>about</b> — who is Arad?</div><div><b>skills</b> — tech stack</div><div><b>projects</b> — selected work</div><div><b>music</b> — trumpet + music technology</div><div><b>stack</b> — engineering stack</div><div><b>status</b> — current portfolio systems</div><div><b>lab</b> — interactive lab</div><div><b>clear</b> — clear terminal</div><div><b>open github</b> — GitHub profile</div><div><b>open kook</b> — KookTools</div><div><b>palette</b> — Command Palette</div><div><b>whoami</b> — current developer</div>')}
function safeCommand(raw){return raw.replaceAll('<','&lt;').replaceAll('>','&gt;')}
$('#terminalForm').onsubmit=e=>{e.preventDefault();const raw=tInput.value.trim(),cmd=raw.toLowerCase();if(!raw)return;print(`<div><span class="green">arad@portfolio:~$</span> ${safeCommand(raw)}</div>`);tInput.value='';if(cmd==='help')help();else if(cmd==='clear')out.innerHTML='';else if(cmd==='whoami')print('<span class="purple">Arad Zabeti</span> — developer / builder / music-tech explorer.');else if(cmd==='about')print('Developer focused on <span class="accent">software, AI, automation and music technology</span>.');else if(cmd==='skills'||cmd==='stack')print('<span class="accent">Engineering:</span> Python · FastAPI · JavaScript · PostgreSQL · Redis · Docker · n8n · AI Agents · Git · Linux');else if(cmd==='projects')print('<span class="purple">Featured:</span> KookTools · Arad Music OS · Telegram systems · Interactive Portfolio');else if(cmd==='music')print('<span class="accent">Music corner:</span> 🎺 Trumpet · Arban · Music Technology · KookTools · Arad Music OS');else if(cmd==='status')print('<span class="green">SYSTEMS ONLINE</span><br>Portfolio · GitHub Pages · GitHub Actions · Snake · Spotify workflow');else if(cmd==='lab'){closeTerminal();$('#lab').scrollIntoView({behavior:'smooth'});return}else if(cmd==='palette'){openPalette();return}else if(cmd==='open github'){window.open('https://github.com/AradZabeti','_blank')}else if(cmd==='open kook'){window.open('https://kooktools.netlify.app','_blank')}else print(`<span class="dim">command not found:</span> ${safeCommand(cmd)}. Type <b>help</b>.`)};
function closeModals(){closePalette();closeTerminal()}document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPalette()}if(e.key==='Escape')closeModals()});
let selected=0;input.addEventListener('keydown',e=>{const items=$$('.cmd');if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(!items.length)return;selected=(selected+(e.key==='ArrowDown'?1:-1)+items.length)%items.length;items.forEach((x,i)=>x.classList.toggle('selected',i===selected))}if(e.key==='Enter'&&items[selected])items[selected].click()});
$$('.project[data-demo]').forEach(x=>x.onclick=e=>{if(e.target.closest('.project-action')){openTerminal();setTimeout(()=>{tInput.value='demo music';$('#terminalForm').dispatchEvent(new Event('submit',{cancelable:true,bubbles:true}))},80)}});
const hue=$('#hue'),orb=$('#colorOrb'),value=$('#colorValue');function updateColor(){const h=hue.value;orb.style.background=`hsl(${h} 80% 70%)`;orb.style.boxShadow=`0 0 70px hsla(${h} 80% 65% /.25)`;value.textContent='#'+h.toString().padStart(3,'0')};hue.oninput=updateColor;
addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',`${e.clientX}px`);document.documentElement.style.setProperty('--my',`${e.clientY}px`)},{passive:true});
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;$('#progress').style.width=(max?(scrollY/max)*100:0)+'%'},{passive:true});
const sections=$$('main section[id]'),nav=$$('.navlinks a');addEventListener('scroll',()=>{let id='';sections.forEach(s=>{if(scrollY>=s.offsetTop-180)id=s.id});nav.forEach(a=>a.classList.toggle('active',a.hash==='#'+id))},{passive:true});
